updates base.html
zagaran/sample-django-app pull request #28
Opened 2021-11-15 21:25 UTC by kyfantaz

2021-11-17 19:28 UTC, alvinsiu requested changes

2021-11-17 19:28 UTC, alvinsiu commented on maintainers.md
> +Test your generated `sample-django-app` and push to https://github.com/zagaran/sample-django-app
:+1:

2021-11-17 19:28 UTC, alvinsiu commented on common/templates/base_templates/base.html
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"
Bootstrap 5 no longer requires jquery, and the bootstrap.bundle.min.js already includes popper, so I think it's sufficient to remove both jquery and popper.

2022-08-05 17:37 UTC, zags commented
Changes already on master

2022-08-05 17:37 UTC, closed without merging